import { CommonModule } from '@angular/common';
import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { WorkflowService } from '../workflow.service';
import { WorkflowDefinition, WorkflowStep } from '../models/workflow.model';
import { LanguageService } from '../language.service';

type TriggerType = 'form' | 'email' | 'schedule' | 'manual';
type Frequency = 'high' | 'daily' | 'weekly' | 'sporadic';

interface WizardAnswers {
  goal: string;
  currentPlace: string;
  trigger: TriggerType;
  frequency: Frequency;
  team: string;
  approver: string;
  hasApproval: boolean;
  approvalLevels: 'single' | 'multi';
  escalationCriteria: string;
  mainSteps: string;
  requiredData: string;
  conditionalRule: string;
  conditionalAction: string;
  integrations: string[];
  integrationActions: string;
  sensitiveProcess: boolean;
  kpi: string;
  notifyAudience: string;
  mode: 'recommended' | 'advanced';
}

@Component({
  selector: 'app-workflow-wizard',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './workflow-wizard.component.html',
  styleUrl: './workflow-wizard.component.css',
  host: { class: 'flex-1 flex flex-col' }
})
export class WorkflowWizardComponent {
  private workflowService = inject(WorkflowService);
  private router = inject(Router);
  lang = inject(LanguageService);

  loading = signal(false);
  createdId = signal<string | null>(null);

  private readonly wizardTranslations: Record<'en' | 'es', Record<string, string>> = {
    en: {
      step1: 'Context',
      step2: 'Start Event',
      step3: 'Actors',
      step4: 'Key Steps',
      step5: 'Rules',
      step6: 'Integrations',
      step7: 'Outcome',
      step8: 'Confirmation',
      autoActive: 'Auto-generated (active)',
      autoDraft: 'Auto-generated (draft)',
      fallbackWorkflowName: 'New workflow',
      fallbackRuleWhen: 'amount > 500',
      fallbackRuleThen: 'Escalate for approval',
      noApproval: 'N/A',
      labelInfoFor: 'Information for',
      descriptionPrefix: 'Generated by assistant',
      descriptionSuffix: 'starts with',
      descriptionMetric: 'and tracks',
      successPath: 'Notify',
      errorPath: 'Send alert to owner for manual review.',
      notesPrefix: 'Main rule',
      notesIntegrations: 'Integrations',
      defaultSteps: 'Receive,Review,Decide,Notify'
    },
    es: {
      step1: 'Contexto',
      step2: 'Inicio del proceso',
      step3: 'Actores',
      step4: 'Pasos clave',
      step5: 'Reglas',
      step6: 'Integraciones',
      step7: 'Resultado',
      step8: 'Confirmación',
      autoActive: 'Auto-generado (activo)',
      autoDraft: 'Auto-generado (borrador)',
      fallbackWorkflowName: 'Nuevo workflow',
      fallbackRuleWhen: 'monto > 500',
      fallbackRuleThen: 'Escalar a aprobación',
      noApproval: 'No aplica',
      labelInfoFor: 'Información para',
      descriptionPrefix: 'Generado por asistente',
      descriptionSuffix: 'inicia por',
      descriptionMetric: 'y mide',
      successPath: 'Notificar a',
      errorPath: 'Enviar alerta al responsable para revisión manual.',
      notesPrefix: 'Regla principal',
      notesIntegrations: 'Integraciones',
      defaultSteps: 'Recibir,Revisar,Decidir,Notificar'
    }
  };

  steps = computed(() => ([
    this.t('step1'),
    this.t('step2'),
    this.t('step3'),
    this.t('step4'),
    this.t('step5'),
    this.t('step6'),
    this.t('step7'),
    this.t('step8')
  ]));

  current = signal(0);

  answers: WizardAnswers = {
    goal: '',
    currentPlace: '',
    trigger: 'form',
    frequency: 'daily',
    team: '',
    approver: '',
    hasApproval: true,
    approvalLevels: 'single',
    escalationCriteria: '',
    mainSteps: '',
    requiredData: '',
    conditionalRule: '',
    conditionalAction: '',
    integrations: [],
    integrationActions: '',
    sensitiveProcess: false,
    kpi: '',
    notifyAudience: '',
    mode: 'recommended'
  };

  generatedSpec = computed(() => this.buildSpec());
  generatedWorkflow = computed(() => this.toWorkflowDefinition());

  canContinue = computed(() => {
    switch (this.current()) {
      case 0:
        return !!this.answers.goal.trim() && !!this.answers.currentPlace.trim();
      case 1:
        return this.answers.trigger !== undefined && (this.answers.trigger === 'manual' || !!this.answers.frequency);
      case 2:
        return !!this.answers.team.trim() && (!this.answers.hasApproval || !!this.answers.approver.trim());
      case 3:
        return !!this.answers.mainSteps.trim() && !!this.answers.requiredData.trim();
      case 4:
        return !!this.answers.conditionalRule.trim() && !!this.answers.conditionalAction.trim();
      case 5:
        return this.answers.integrations.length > 0 && !!this.answers.integrationActions.trim();
      case 6:
        return !!this.answers.kpi.trim() && !!this.answers.notifyAudience.trim();
      default:
        return true;
    }
  });

  next(): void {
    if (!this.canContinue() || this.current() >= this.steps().length - 1) return;
    this.current.set(this.current() + 1);
  }

  prev(): void {
    if (this.current() === 0) return;
    this.current.set(this.current() - 1);
  }

  toggleIntegration(name: string): void {
    if (this.answers.integrations.includes(name)) {
      this.answers.integrations = this.answers.integrations.filter(item => item !== name);
      return;
    }
    this.answers.integrations = [...this.answers.integrations, name];
  }

  saveDraft(): void {
    this.persist('draft');
  }

  activateWorkflow(): void {
    this.persist('active');
  }

  private persist(state: 'draft' | 'active'): void {
    const workflow = this.generatedWorkflow();
    workflow.category = state === 'active' ? this.t('autoActive') : this.t('autoDraft');
    this.loading.set(true);
    this.workflowService.createWorkflow(workflow).subscribe({
      next: (created: WorkflowDefinition) => {
        this.loading.set(false);
        this.createdId.set(created.id);
        void this.router.navigate(['/builder', created.id]);
      },
      error: () => this.loading.set(false)
    });
  }

  private buildSpec() {
    const baseSteps = this.answers.mainSteps
      .split(',')
      .map(s => s.trim())
      .filter(Boolean);

    const normalizedSteps = baseSteps.length > 0 ? baseSteps : this.t('defaultSteps').split(',');
    const rules = [
      {
        when: this.answers.conditionalRule || this.t('fallbackRuleWhen'),
        then: this.answers.conditionalAction || this.t('fallbackRuleThen')
      }
    ];

    return {
      workflow: {
        name: this.answers.goal || this.t('fallbackWorkflowName'),
        trigger: {
          type: this.answers.trigger,
          frequency: this.answers.trigger === 'manual' ? 'on_demand' : this.answers.frequency,
          source: this.answers.currentPlace
        },
        actors: {
          team: this.answers.team,
          approver: this.answers.hasApproval ? this.answers.approver : this.t('noApproval'),
          approvalLevels: this.answers.hasApproval ? this.answers.approvalLevels : 'none',
          escalationCriteria: this.answers.approvalLevels === 'multi' ? this.answers.escalationCriteria : ''
        },
        steps: normalizedSteps,
        requiredData: this.answers.requiredData,
        rules,
        integrations: this.answers.integrations.map(integration => ({
          provider: integration,
          action: this.answers.integrationActions
        })),
        controls: {
          sensitiveProcess: this.answers.sensitiveProcess,
          kpi: this.answers.kpi,
          notifyAudience: this.answers.notifyAudience,
          mode: this.answers.mode
        }
      }
    };
  }

  private toWorkflowDefinition(): Partial<WorkflowDefinition> {
    const spec = this.buildSpec().workflow;
    const cards = spec.steps.map((stepTitle, index): WorkflowStep => ({
      id: `step_${index + 1}`,
      title: stepTitle,
      fields: [
        {
          id: `field_${index + 1}_summary`,
          type: 'longText',
          label: `${this.t('labelInfoFor')}: ${stepTitle}`,
          required: index === 0
        }
      ],
      navigation: {
        nextStep: index < spec.steps.length - 1 ? `step_${index + 2}` : undefined
      },
      position: { x: 100 + index * 420, y: 120 },
      dimensions: { width: 360, height: 620 }
    }));

    return {
      name: spec.name,
      description: `${this.t('descriptionPrefix')}: ${this.t('descriptionSuffix')} ${spec.trigger.type} ${this.t('descriptionMetric')} ${spec.controls.kpi}.`,
      successPath: `${this.t('successPath')} ${spec.controls.notifyAudience}`,
      errorHandlingPath: this.t('errorPath'),
      notes: `${this.t('notesPrefix')}: ${spec.rules[0].when} => ${spec.rules[0].then}. ${this.t('notesIntegrations')}: ${spec.integrations.map(i => i.provider).join(', ')}`,
      steps: cards,
      totalSteps: cards.length
    };
  }

  t(key: string): string {
    return this.wizardTranslations[this.lang.currentLang()]?.[key] ?? this.wizardTranslations.en[key] ?? key;
  }
}
